### ISSUE TITLE
for testing, doesn'need to be zipped

### ISSUE THREAD

**Issue by opto** [thundernest/sample-extensions#10]
the instruction tells to zip and temporarily install.

If temporarily installed, it is sufficient to 'load' an addonfile in the dialog, e.g. point to the manifest file.
zipping before is not needed (75b)

**Comment by jobisoft** [comment]
The text in the readme says "either". So it is correct. You can either zip it OR load it via debug addons. But one could rephrase the part "navigate to your code" and say "select manifest.json" instead.

**Comment by jobisoft** [comment]
Created PR: https://github.com/thundernest/sample-extensions/pull/11

**Comment by jobisoft** [comment]
@opto : Is the proposed change in the spirit of this issue?

**Comment by opto** [comment]
fine. thanks, Klaus
