### ISSUE TITLE
Trying out message compose

### ISSUE THREAD

**Issue by majubewi** [thundernest/sample-extensions#13]
I have found these examples and I want to modify the parameters of a thunderbird sending email window. I want to add cc, bcc and so forth.

I have tried the composeBody example for my extension but it keeps telling me that:

"browser.compose.setComposeDetails is not a function"

What is the problem?

**Comment by darktrojan** [comment]
At a guess, I'd say the problem is you're using Thunderbird 68 and these new functions are not in that version. Which is a reminder to me that I should add minimum version numbers to each example.
