### ISSUE TITLE
Add-on for send-unsent-messages-without-attachments

### ISSUE THREAD

**Issue by b18050** [thundernest/sample-extensions#14]
@darktrojan An add-on which will add an option to send unsent messages without attachments . 
While travelling on a plane, I check my downloaded emails and may reply /send many emails . Some are brief , others  have large attachments.
When I connect to a mobile network with low data range. Thunderbird tries to deliver the emails in Outbox in chronological order. If the first on happens to be a low-priority
email with large attachment,it may take a very long time or even timeout. Short high-priority emails later in the Outbox are blocked.

**Comment by b18050** [comment]
@darktrojan

**Comment by jobisoft** [comment]
This has not received an answer for 4 years. I am going to close it. This is not the right place to ask for add-ons with specific features. 

You can either do that on the [public add-on developer mailing list](https://thunderbird.topicbox.com/groups/addons), or [request it as a feature for Thunderbird itself](https://connect.mozilla.org/t5/ideas/idb-p/ideas/label-name/thunderbird).
