### ISSUE TITLE
Alert when sending that checks contact metadata for flag

### ISSUE THREAD

**Issue by canDry** [thundernest/sample-extensions#25]
E.g. when SEND is pressed and a particular contact e.g. where they have a value "NO-EMAIL" in a custom contact field - the extension should not proceed sending, but pop up with an alert.
  
There's also a case where certain contacts should only be sent email using a particular "FROM" email address (i.e. corporate vs. personal)...   similarly the extension should not proceed sending, but pop up with an alert.

**Comment by jobisoft** [comment]
Which example extension are you referring to?

**Comment by canDry** [comment]
> Which example extension are you referring to?

Sorry... if this was the wrong approach.  I was hoping to elicit a solution for these user cases. 
  
This is one of the only places I've seen examples of TB extensions!

**Comment by jobisoft** [comment]
You could use the onBeforeSend event.
https://webextension-api.thunderbird.net/en/78/compose.html#onbeforesend-tab-details

You can reach us here for help on add-on development:
https://developer.thunderbird.net/add-ons/community
