### ISSUE TITLE
Most of these sample extensions dont work

### ISSUE THREAD

**Issue by bkd** [thundernest/sample-extensions#27]
Name 	Thunderbird
Version 	91.7.0
Build ID 	20220305171341
Distribution ID 	ubuntu-snap-build

So I've gone through pretty much every extension, and tried. I'm not able to load any temporary addon - files are not found leading to errors about encoding...

e.g. Just testing the layout example

First tried as a temp addon -

"The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. [layout.html](moz-extension://cfe05d3e-04a4-4678-b20a-88725292327a/layout.html)"

So naturally thinking that I had to check the UTF-8 in the HTML as meta tag. No - seems fine.  Locales are not found when loading the temp add on. Tried as XPI /  ZIP - same again, and seems that TB isnt loading the file at all. 

Not sure if its a breaking change, or unique to this build...

**Comment by jobisoft** [comment]
I cannot confirm this on a standard Ubuntu install:

![grafik](https://user-images.githubusercontent.com/5830621/161059041-255a2da1-a9bd-418a-a0af-3a3eb26675fd.png)

The reported encoding error is in yellow (is it?), which means it is a warning and non-fatal. I have no idea why the add-ons do not work for you. They all should work as temporary installs.

Can I have a screenshot of the "files not found" error message?
