### ISSUE TITLE
Help with Theming

### ISSUE THREAD

**Issue by Stanzilla** [thundernest/sample-extensions#3]
Hey there, not sure if this is the correct place but is there something like the big graphic on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme that explains which part is called what in the theming manifest for Thunderbird?

**Comment by darktrojan** [comment]
Thanks for the suggestion, there isn't one as far as I know. I'll see about getting a diagram made, but in the meantime, the names and what they do are almost exactly the same as they are in Firefox.

**Comment by Stanzilla** [comment]
@darktrojan there are a few extra elements in Thunderbird though, like the quick filter bar etc

![image](https://user-images.githubusercontent.com/75278/63593472-5f969500-c5b4-11e9-9d78-d89acf21cd79.png)
I currently don't see a way to theme them
