### ISSUE TITLE
Error calling messenger.messageDisplay.getDisplayedMessage on .eml mail

### ISSUE THREAD

**Issue by martinclauss** [thundernest/sample-extensions#30]
Thunderbird version: 102.6.0 (64-bit)
OS: Linux

Hello :)

I encountered a strange behavior when working with .eml attachments. If I run the sample extension https://github.com/thundernest/sample-extensions/tree/master/messageDisplay on a "normal" mail it works just fine. But, if I have an *.eml attachment*, open it and click the extension's button, it gives me the following error (console output):

```
msgHdr.getProperty is not a function ext-mail.js:1753
    convertMessage chrome://messenger/content/parent/ext-mail.js:1753
    getDisplayedMessage chrome://messenger/content/parent/ext-messageDisplay.js:142
    getDisplayedMessage self-hosted:1121
    result resource://gre/modules/ExtensionParent.jsm:1035
    withCallContextData resource://gre/modules/ExtensionParent.jsm:524
    result resource://gre/modules/ExtensionParent.jsm:1034
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:534
    result resource://gre/modules/ExtensionParent.jsm:1033
    callAndLog resource://gre/modules/ExtensionParent.jsm:986
    recvAPICall resource://gre/modules/ExtensionParent.jsm:1032
    InterpretGeneratorResume self-hosted:1429
    AsyncFunctionNext self-hosted:632
Error: An unexpected error occurred undefined
Message displayed in tab 2: eml attachment test background.js:2:11
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. fetch>UID>.INBOX>14690
```

The problem seems to start here:

https://github.com/thundernest/sample-extensions/blob/master/messageDisplay/popup.js#L6

I work on an extension myself where the same error occurs and I don't know how to fix this problem...

Any help would be very appreciated :)

Best
Martin

**Comment by martinclauss** [comment]
Hey there! :)

Can anyone point me into a direction that could solve this problem?

Thanks!

Best
Martin

**Comment by jobisoft** [comment]
I can confirm this is a bug. It may be a different bug on Daily (TB 112), but it is still a bug. Could you file a report here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird&component=Add-Ons%3A+Extensions+API

Thanks!

**Comment by martinclauss** [comment]
I think this might be very related: https://bugzilla.mozilla.org/show_bug.cgi?id=1644038 What do you think? Cheers! :)

**Comment by jobisoft** [comment]
I lost track of this issue. Could you confirm that it is fixed in Thunderbird 128 and Thunderbird 115?

**Comment by martinclauss** [comment]
Yes, seems to be fixed 😊 

Thanks!
