### ISSUE TITLE
hello-world example does not display icon or popup in 102.10.1 (64-bit)

### ISSUE THREAD

**Issue by pflagerd** [thundernest/sample-extensions#31]
OS: KDE Neon 22.04 Guest running under KVM/QEMU on Ubuntu 22.04
Thunderbird: 102.10.1 (64-bit) Flatpak
hello-world commit used: b8855e6dc919d5456d30d9553fc225e5ce95f2fe

hello-world button appears on main toolbar without icon:

![image](https://user-images.githubusercontent.com/246217/235830839-d13f5277-d71f-435f-bb54-e7780ef3ff52.png)

Hovering over hello-world button causes title to display:

![image](https://user-images.githubusercontent.com/246217/235831026-ec5c5c0e-ca70-4956-8627-3bfce831857a.png)

Clicking on the button causes a vertical line to be displayed briefly, and a small oblong "bubble" to appear:

![image](https://user-images.githubusercontent.com/246217/235831217-9bca2c7d-bc8e-428c-9f6d-72ecf1e878aa.png)

Loading mainPopup/popup.html in Firefox seems to work fine:

![image](https://user-images.githubusercontent.com/246217/235831432-c29126af-ebb7-49d5-ba86-e2163e72dc8a.png)

I've checked file permissions of the files and directory to make sure they are accessible, have loaded the icons in a viewer to confirm that they are okay.  I loaded the extension with Load Temporary Add-on...

![image](https://user-images.githubusercontent.com/246217/235831732-6157cf43-2f2a-4f48-9fad-77310dcba79c.png)

Here's what the inspector shows (which makes no sense to me):

![image](https://user-images.githubusercontent.com/246217/235831828-9dd0c790-7520-4021-8e2f-8297b0f65186.png)

**Comment by jobisoft** [comment]
Thanks for your report. This seems to be a flatpack issue which does not allow accessing all the files. Seems to be
https://bugzilla.mozilla.org/show_bug.cgi?id=1909765

It should work, if you zip the extension and install it normally. Closing this issue here. Please add further comments regarding this issue in the linked bug.
