### ISSUE TITLE
How do I determine the attachment for messages with manifest v3?

### ISSUE THREAD

**Issue by LaKanDoR** [thundernest/sample-extensions#33]
I sent myself an email with an attachment, but I don't see any way to read the file attachment within the "message" and, for example, process it further

i use messenger.messages.onNewMailReceived.addListener(mail_checker); for calling and IMAPS Server, there is no "Attachments" or something else.

![image](https://github.com/thunderbird/sample-extensions/assets/3150828/db9b20e4-a9fb-46e7-ad9c-d7f52a22bab1)

i can't see attachments if i use this to load the message object content while opening the email in thunderbird.

```
background.js

browser.messageDisplay.onMessageDisplayed.addListener((tab, message) => {
  console.log(`Message displayed in tab ${tab.id}: ${message.subject}`);
  console.log(message);
});

```
Thank you for helping me :-)

**Comment by LaKanDoR** [comment]
In the documentation is something mentioned but i don't know exaclty what messageId is meant. 
message.id (?) - a internal number.

```
//backgroudn.ks
async function mail_display(tab, message) {
  console.log(`Message displayed in tab ${message.messageId}: ${message.subject}`);
  console.log(message.id); 
  try {
 

    let attachments = await browser.messages.listAttachments(message.id);
    console.log(attachments);
    for (let att of attachments) {
      let file = await browser.messages.getAttachmentFile(messageId, att.partName);
      console.log(file);
      let content = await file.text();
    }
  } catch(error) {
    console.log(`Fehler beim Abrufen der Attachments: ${error}`);
  }
}
browser.messageDisplay.onMessageDisplayed.addListener(mail_display);
```

Thank you all 🕊️

**Comment by jobisoft** [comment]
Hi!

´message.messageId´ does not exist, only ´message.id´. The definition of the MessageHeader is here:
https://webextension-api.thunderbird.net/en/stable/messages.html#messageheader

That id is an internal integer identifier of the message. It is only valid in the session it was returned, but will point to a different message in other sessions (for example, after restarting Thunderbird)

**Comment by LaKanDoR** [comment]
> Hi!
> 
> ´message.messageId´ does not exist, only ´message.id´. The definition of the MessageHeader is here: https://webextension-api.thunderbird.net/en/stable/messages.html#messageheader
> 
> That id is an internal integer identifier of the message. It is only valid in the session it was returned, but will point to a different message in other sessions (for example, after restarting Thunderbird)

Hi @jobisoft,
by the way nice repro, nice job 👍
but there is no example of how to work with file attachments, right?

How can I find out the message ID?

> Note
> 
> When the term messageId is used in these documents, it doesn’t refer to the Message-ID email header. It is an internal tracking number that does not remain after a restart. Nor does it follow an email that has been moved to a different folder.
> https://webextension-api.thunderbird.net/en/115/messages.html


The message ID is mentioned right at the top of the messages API, but it is not explained in detail where you get it.

I would like to build a free extension that transmits the files in the attachments directly to https://www.Virustotal.com or https://www.hybrid-analysis.com/ via API.

For my extension, access to the attachment is mandatory. I would have expected the message.messageId or even message.attachments within the messages object.

![image](https://github.com/thunderbird/sample-extensions/assets/3150828/02ceaf66-5fb8-43e9-8eaa-8ee6e0e81948)

it's true there is an Attachments but how to access it?
`let attachments = await browser.messages.listAttachments(message.id);`

console.log(attachments) is empty.

**Comment by LaKanDoR** [comment]
okay i found a solution that is working:
```
// background.js in Thunderbird extension
async function mail_display(tab, message) {
  // Log message: "Message displayed in tab {message.id}: {message.subject}"
  console.log(`Message displayed in tab ${message.id}: ${message.subject}`);

  // Try to load the full message
  try {
    // Save the full message in the message_full variable
    message_full = await browser.messages.getFull(message.id);

    // Log the message (optional)
    //console.log(message);

    // Call the listAttachments() method to get the list of attachments
    let attachments = await browser.messages.listAttachments(message.id);

    // Log the attachments
    console.log(attachments);

    // Iterate over the attachments
    for (let att of attachments) {
      // Call the getAttachmentFile() method to get the file for the attachment
      let file = await browser.messages.getAttachmentFile(message.id, att.partName);

      // Call the text() method to get the attachment content as text
      let content = await file.text();

      // Log the attachment content
      console.log(content);
    }
  } catch (error) {
    // Log the error message
    console.log(`Error with loading the Attachments: ${error}`);
  }
}

browser.messageDisplay.onMessageDisplayed.addListener(mail_display);

```

Note: 1. Restart Thunderbird 2. It doesn't seem to work if the email is openPGP encrypted

**Comment by jobisoft** [comment]
You are correct, we are missing example snippets. I will add more examples to the docs on Q1.2024.

Glad you got it working!

PGP support is on the too list as well.
